name: flutter_ui_challenges
description: "Flutter UI Challenges."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'
  flutter: ^3.19.3

dependencies:
  collection: 1.18.0
  drift: 2.16.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: 2.5.1
  go_router: 13.2.1
  http: 1.2.1
  path: 1.9.0
  path_provider: 2.1.2
  riverpod_annotation: 2.3.5
  sqlite3: 2.4.0
  sqlite3_flutter_libs: 0.5.20

dev_dependencies:
  build_runner: 2.4.8
  drift_dev: 2.16.0
  flutter_lints: 3.0.1
  flutter_test:
    sdk: flutter
  lint: 2.3.0
  riverpod_generator: 2.4.0
  riverpod_lint: 2.3.10

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/

# RPS
# Запуск — $ rps [script_name]
scripts:
  get: flutter pub get
  test: flutter test lib
  gen: dart run build_runner build --delete-conflicting-outputs
  watch: dart run build_runner watch

