name: flutter_ui_challenges
description: "Flutter UI Challenges."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'
  flutter: ^3.19.4

dependencies:
  collection: 1.18.0
  decimal: 3.0.0
  fl_chart: 0.68.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^3.0.0-dev.3
  flutter_svg: ^2.0.10+1
  go_router: 14.1.4
  intl: 0.19.0
  riverpod_annotation: ^3.0.0-dev.3

dev_dependencies:
  build_runner: 2.4.10
  flutter_lints: 4.0.0
  flutter_test:
    sdk: flutter
  lint: 2.3.0
  riverpod_generator: ^3.0.0-dev.11
  riverpod_lint: ^3.0.0-dev.4

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/vectors/
    - assets/vectors/cryptocurrency/
    - assets/vectors/news/

  fonts:
    - family: Britanica
      fonts:
        - asset: assets/fonts/Britanica/Britanica Light.ttf
        - asset: assets/fonts/Britanica/Britanica Light Italic.ttf
          style: italic
        - asset: assets/fonts/Britanica/Britanica Regular.ttf
        - asset: assets/fonts/Britanica/Britanica Bold.ttf
        - asset: assets/fonts/Britanica/Britanica Extra Bold.ttf
        - asset: assets/fonts/Britanica/Britanica Black.ttf
    - family: Britanica Semi Expanded
      fonts:
        - asset: assets/fonts/Britanica/Britanica Semi Expanded Regular.ttf
        - asset: assets/fonts/Britanica/Britanica Semi Expanded Bold.ttf
    - family: Britanica Expanded
      fonts:
        - asset: assets/fonts/Britanica/Britanica Expanded Bold.ttf
        - asset: assets/fonts/Britanica/Britanica Expanded Extra Bold.ttf

# RPS
# Запуск — $ rps [script_name]
scripts:
  get: flutter pub get
  test: flutter test lib
  gen: dart run build_runner build --delete-conflicting-outputs
  watch: dart run build_runner watch
  assets: spider build

