name: flutter_ui_challenges
description: "Flutter UI Challenges."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.5.2 <4.0.0"
  flutter: ^3.24.2

dependencies:
  collection: 1.18.0
  decimal: 3.0.2
  fl_chart: 0.69.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: 2.5.1
  flutter_svg: 2.0.10
  go_router: 14.2.7
  intl: 0.19.0
  riverpod_annotation: 2.3.5
  vector_graphics: 1.1.11

dev_dependencies:
  build_runner: 2.4.12
  flutter_lints: 4.0.0
  flutter_test:
    sdk: flutter
  lint: 2.3.0
  riverpod_generator: 2.4.3
  riverpod_lint: 2.3.13
  vector_graphics_compiler: 1.1.11

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/vectors/
    - assets/images/twitter_embed_card/
    - assets/vectors/crypto_platform_layout/

    # SVGs to be transformed
    - path: assets/vectors/twitter_embed_card/
      transformers:
        - package: vector_graphics_compiler
    - path: assets/vectors/interactive_page_flip/
      transformers:
        - package: vector_graphics_compiler

  fonts:
    - family: Britanica
      fonts:
        - asset: assets/fonts/Britanica/Britanica Light.ttf
        - asset: assets/fonts/Britanica/Britanica Light Italic.ttf
          style: italic
        - asset: assets/fonts/Britanica/Britanica Regular.ttf
        - asset: assets/fonts/Britanica/Britanica Bold.ttf
        - asset: assets/fonts/Britanica/Britanica Extra Bold.ttf
        - asset: assets/fonts/Britanica/Britanica Black.ttf
    - family: Britanica Semi Expanded
      fonts:
        - asset: assets/fonts/Britanica/Britanica Semi Expanded Regular.ttf
        - asset: assets/fonts/Britanica/Britanica Semi Expanded Bold.ttf
    - family: Britanica Expanded
      fonts:
        - asset: assets/fonts/Britanica/Britanica Expanded Bold.ttf
        - asset: assets/fonts/Britanica/Britanica Expanded Extra Bold.ttf

# RPS
# Запуск — $ rps [script_name]
scripts:
  get: flutter pub get
  test: flutter test lib
  gen: dart run build_runner build --delete-conflicting-outputs
  watch: dart run build_runner watch
  assets: spider build
